name: Testing
on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  testing-and-sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install and verify dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pylint
        run: |
          pylint --fail-under=1.0 app
